version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  product-service:
    image: dilesp/product-service:latest
    build:
      context: ./ProductService
      dockerfile: Dockerfile
      args:
        JAR_FILE: productservice.jar
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

  user-service:
    image: dilesp/user-service:latest
    build:
      context: ./UserService
      dockerfile: Dockerfile
      args:
        JAR_FILE: user-service.jar
    container_name: userservice
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

  cart-service:
    image: dilesp/cart-service:latest
    build:
      context: ./CartService
      dockerfile: Dockerfile
      args:
        JAR_FILE: cartservice.jar
    container_name: cart-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

  api-gateway:
    image: dilesp/apigateway-service:latest
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
      args:
        JAR_FILE: apigateway.jar
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
