apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: UserService
  template:
    metadata:
      labels:
        app: UserService
    spec:
      containers:
        - name: product-service
          image: dilesp/user-service:latest
          ports:
            - containerPort: 8082