#spring:
#  application:
#    name: user-service # or product-service, cart-service, etc.
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: cart-service-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"